#!/usr/bin/env bash
# Displays information about subdomains
function audit_domain() {
    domain="$1"
    subdomain="$2"
    
    # Define an array of subdomains to audit
    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi
    
    # Iterate over the subdomains array
    for sub in "${subdomains[@]}"; do
	
	# Fetch DNS records for the correct subdomain
	result=$(dig +short "$sub.$domain")

	# Check if the DNS record is not empty
	if [ -n "$result" ]; then
	    # Extract record type and destination from the DNS record
	    record_type=$(echo "$result" | awk '{print $4}')
	    destination=$(echo "$result" | awk '{print $1}')
	    echo "The subdomain $sub is a $record_type record and points to $destination"
	else
            # Handle the case where the subdomain does not have a valid DNS record
	    echo "The subdomain $sub does not have a valid DNS record."
	fi
    done
}

# Check if the correct number of arguments is provided
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

# Run the audit_domain function with provided arguments
audit_domain "$1" "$2"
