#!/usr/bin/env bash
#  Transfers a file from a client to a server

#  Check for correct number of arguments
if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

#  Assign arguments to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

#  Distable strict host key checking for scp
scp_options="-o StrictHostKeyChecking=no"

#  Tranfer the file to the user's home directory on the server
scp $scp_options -i "$ssh_key_path" "$file_path" "$username@$server_ip:~/"
