#!/usr/bin/env bash
#  Install nginx on your web-01 server Nginx should be listening on port 80
#  Update the package list and install Nginx
apt-get update -y
apt-get install -y nginx

#  Create a custon Nginx configuration file
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        echo 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

#  Reload Nginx to apply the new configuration
service nginx reload

#  Clean up
apt-get clean
