#!/usr/bin/env bash
#  Install nginx on your web-01 server Nginx should be listening on port 80
#  Update the package list and install Nginx
sudo apt-get update

if ! dpkg -l | grep -q nginx; then
    sudo apt-get install -y nginx
fi

#  Create an HTML file with "Hello World" content
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

#  Nginx configuration file to listen to port 80 and serve the default site
sudo sed -i 's/default_server//g' /etc/nginx/sites-available/default

#  Find the Nginx master process ID
nginx_master_pid=$(ps aux | grep '[n]ginx: master process' | awk '{print $2}')

#  Gracefully stop Nginx
sudo kill -QUIT "$nginx_master_pid"

#  Reload Nginx to apply the new configuration
sudo nginx

#  Cleanly exit the script
exit 0
