#!/usr/bin/env bash
#  Configures the Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
#  Update the package list and install Nginx
sudo apt-get update

if ! dpkg -l | grep -q nginx; then
    sudo apt-get install -y nginx
fi

sudo rm /etc/nginx/sites-enabled/custom404

#  Create a custom 404 error page
echo "
server {
    listen 80 default_server;
    server_name 34.224.95.50;

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/custom404 > /dev/null

#  Create the custom 404 error page content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

#  Create a symbolic link to enable the new site configuration
sudo ln -s /etc/nginx/sites-available/custom404 /etc/nginx/sites-enabled

#  Test the Nginx configuration
sudo nginx -t

#  Gracefully reload Nginx
sudo nginx -s reload
