#!/usr/bin/env bash
#displays the PID, along with the process name, 
#of processes whose name contain the word bash.
pids=$(pgrep -f bash)
for pid in $pids
do
    process_name=$(< "/proc/$pid/comm")
    echo "$pid $process_name"
done
