#!/usr/bin/env bash
#Displays To infinity and beyond indefinitely, With a 
#sleep 2 in between each iteration
#Displays I am invincible!!! when receiving a SIGTERM signal
terminate_handler() {
    echo "I am invincible!!!"
}

trap terminate_handler SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
