#!/usr/bin/env bash
#Prints the phrase Best School 10 times, but for the 9th iteration, 
#displays Best School and then Hi on a new line.
counter=1
while [ $counter -le 10 ]
do
    echo "Best School"
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi
    (( counter = counter + 1 ))
done
