#!/usr/bin/env bash
#Prints Best School, looping from 1 to 10
#For the 4th loop it prints bad luck
#For the 8th loop it prints good luck 
counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
        echo "bad luck"
    elif [ $counter -eq 8 ]
    then 
        echo "good luck"
    else
        echo "Best School"
    fi
    (( counter = counter + 1 ))
done
