#!/usr/bin/env bash
#Prints the time for 2 hours and 59 minutes
#Prints hours 0 to 12
hours=0
while [ $hours -le 12 ]
do
    echo "Hours: $hours"
    minutes=1
    while [ $minutes -le 59 ]
    do
        echo "$minutes"
        (( minutes = minutes + 1 ))
    done
    (( hours = hours + 1 ))
done    
