#!/usr/bin/env bash
#Provides information about school file
file="school"
#check if it exists
if [ -e "$file" ]
then
    echo "$file file exists"
    #Check if its empty
    if [ -s "$file" ]
    then
        echo "$file file is not empty"
    else
        echo "$file file is empty"
    fi
    #Check if the file is a regular file
    if [ -f "$file" ]
    then
        echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi
