#!/usr/bin/env bash
#Configures an Ubuntu sever with localhost resolve to 127.0.0.2
#facebook.com resolve to 8.8.8.8
#backup the current /etc/hosts file
cp /etc/hosts ~/hosts.original

#modify the host file as required
sed -e '/^127\.0\.0\.1/s/localhost/localhost\n127.0.0.2 localhost/' \
    -e 's/^.*facebook.com/8.8.8.8 facebook.com/' ~/hosts.original > ~/hosts.new

#replace the /etc/host file with the modified one
cp -f ~/hosts.new /etc/hosts

#clean up temporary files
rm -f ~/hosts.origional ~/hosts.new
