#!/usr/bin/env bash
# Creates an nginx user and ensures nginx is listening on all active IPs on port 8080

# Create an nginx user
useradd -r nginx

# Modify nginx configuration to run as the nginx user
sed -i 's/^user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Make sure nginx is listening on all active IPs on port 8080
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default

# Reload nginx to apply the changes
service nginx reload

# Check nginx processes and port 8080 availability
grep -f 'ngin[x]'
nc -z 0 8080
